# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente de pago'), (1, 'Pagada'), (2, 'Parcialidad'), (3, 'Cancelada'), (3, 'En Revision')], db_index=True, default=0)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Balance a Favor el valor es Negativo, Saldo Pendiente el valor Positivo', max_digits=8, verbose_name='Balance')),
                ('balance_nuevo', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo a Favor el valor es                                         Negativo, Saldo Pendiente el valor Positivo', max_digits=15, verbose_name='Saldo Nuevo a Favor')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('reporto_cliente', models.BooleanField(default=False)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajero_factura', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_factura', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forma_pago_factura', to='commons.FormaPago')),
            ],
        ),
    ]
