# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-11 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas_admin', '0003_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Sin facturar'), (1, 'Facturado'), (2, 'Cancelado'), (3, 'Parcial')], db_index=True, default=0)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('detalles', models.TextField(blank=True, editable=False, null=True, verbose_name='Detalles')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_credito', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
                ('factura', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito_factura', to='finanzas_admin.Factura')),
            ],
        ),
    ]
