# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True, max_length=100)),
                ('coordenadas', models.CharField(blank=True, max_length=80, verbose_name='Coordenadas')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pagina_web', models.URLField(blank=True, max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=30, verbose_name='RFC/RUC')),
                ('rfc_sat', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='RFC SAT')),
                ('direccion_facturacion', models.TextField(blank=True, max_length=100)),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('facturas_pagadas', models.BooleanField(default=True, verbose_name='\xbfHa pagado todas sus facturas?')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo a Favor si es negativo, Saldo Pendiente si positivo', max_digits=10)),
            ],
        ),
    ]
