# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
                ('visible', models.BooleanField(default=False, verbose_name='Visible para el Cliente')),
                ('moneda', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MXN'), (1, 'USD')], default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
    ]
